# Generated by Django 5.1.4 on 2024-12-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشركة باللغة العربية')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان الفرعي باللغة العربية')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('welcome_message_ar', models.TextField(blank=True, null=True, verbose_name='رسالة الترحيب باللغة العربية')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_home', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('micro_logo', models.ImageField(blank=True, null=True, upload_to='micro_logos/')),
                ('svg_logo', models.FileField(blank=True, null=True, upload_to='svg_logos/')),
                ('small_description', models.TextField(blank=True, null=True)),
                ('small_description_ar', models.TextField(blank=True, null=True, verbose_name='وصف صغير عن الموقع باللغة العربية')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('slider', 'Slider'), ('contact', 'Contact'), ('project', 'Project'), ('brand', 'Brand'), ('service', 'Service'), ('blog', 'Blog'), ('testimonial', 'Testimonial'), ('product', 'Product'), ('about', 'About'), ('feedback', 'Feedback')], max_length=225, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان القسم باللغة العربية')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان الفرعي للقسم باللغة العربية')),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('background_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_show_stores',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_ar',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='in_slider',
        ),
        migrations.RemoveField(
            model_name='requestproduct',
            name='message_ar',
        ),
        migrations.RemoveField(
            model_name='requestproduct',
            name='name_ar',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutsectioncontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='custom_models.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('in_progress', 'تحت المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('in_progress', 'تحت المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='products', to='custom_models.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='custom_models.category'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_type',
            field=models.CharField(blank=True, choices=[('image', 'صورة'), ('video', 'فيديو')], default='image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='custom_models.blog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='custom_models.category')),
            ],
        ),
    ]
