# Generated by Django 5.1.4 on 2024-12-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0002_companyaddress_globalinfo_sectionheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionheader',
            name='botton_show',
            field=models.BooleanField(default=True),
        ),
    ]
