# Generated by Django 5.1.4 on 2024-12-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0003_sectionheader_botton_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
