# Generated by Django 5.1.4 on 2024-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0004_category_description_en_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_2_ar',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_3_ar',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_4',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_4_ar',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_5',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_5_ar',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='sub_title_ar',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title_ar',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sliders/videos/'),
        ),
    ]
