# Generated by Django 5.1.4 on 2024-12-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0005_remove_slider_sub_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
