# Generated by Django 5.1.4 on 2024-12-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0006_slider_sub_title_ar_slider_sub_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionheader',
            name='background_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionheader',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionheader',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
