# Generated by Django 5.1.4 on 2024-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0007_sectionheader_background_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='html_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='html_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
