# Generated by Django 5.1.4 on 2024-12-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0008_aboutsection_html_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionheader',
            name='background',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='background_ar',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='background_en',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='botton_show',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='section_type',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='sub_title_ar',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='sectionheader',
            name='title_en',
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
