# Generated by Django 5.1.4 on 2024-12-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0009_remove_sectionheader_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionheader',
            name='section_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('slider', 'Slider'), ('contact', 'Contact'), ('project', 'Project'), ('brand', 'Brand'), ('service', 'Service'), ('blog', 'Blog'), ('testimonial', 'Testimonial'), ('product', 'Product'), ('about', 'About'), ('feedback', 'Feedback')], max_length=225, null=True),
        ),
    ]
