# Generated by Django 5.1.4 on 2024-12-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0010_sectionheader_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionheader',
            name='html_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='html_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionheader',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
