# Generated by Django 5.1.4 on 2024-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0011_sectionheader_html_content_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='free_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='free_section_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='free_section_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
