# Generated by Django 5.1.4 on 2024-12-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0012_aboutsection_free_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='free_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='free_section_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='free_section_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
