# Generated by Django 5.1.4 on 2024-12-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0013_feedback_free_section_feedback_free_section_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='free_section',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='free_section_ar',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='free_section_en',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title_en',
        ),
    ]
