# Generated by Django 5.1.4 on 2024-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0014_remove_feedback_free_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
