# Generated by Django 5.1.4 on 2024-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0015_alter_feedback_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='icon_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='icon_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
