# Generated by Django 5.1.4 on 2024-12-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0016_feedback_icon_ar_feedback_icon_en_feedback_title_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PagesStructer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='custom_models.pages')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='custom_models.sections')),
            ],
        ),
    ]
