# Generated by Django 5.1.4 on 2024-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0017_pages_sections_pagesstructer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesstructer',
            name='command_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
