# Generated by Django 5.1.4 on 2024-12-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0018_pagesstructer_command_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionHeader',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='html_content_ar',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='html_content_en',
        ),
    ]
