# Generated by Django 5.1.4 on 2024-12-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0019_delete_sectionheader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='free_section',
            new_name='html_content',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='free_section_ar',
            new_name='html_content_ar',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='free_section_en',
            new_name='html_content_en',
        ),
    ]
