# Generated by Django 5.1.4 on 2024-12-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0020_rename_free_section_aboutsection_html_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesstructer',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='custom_models.sections'),
        ),
    ]
