# Generated by Django 5.1.4 on 2024-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0021_alter_pagesstructer_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesstructer',
            name='html_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='html_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='order_ar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='order_en',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
