# Generated by Django 5.1.4 on 2024-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0022_pagesstructer_html_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesstructer',
            name='order_ar',
        ),
        migrations.RemoveField(
            model_name='pagesstructer',
            name='order_en',
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagesstructer',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
