# Generated by Django 5.1.4 on 2024-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0024_service_html_content_service_html_content_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='quote_1',
            new_name='html_content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='quote_1_ar',
            new_name='html_content_ar',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='quote_2',
            new_name='html_content_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quote_2_ar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quote_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quote_3_ar',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
