# Generated by Django 5.1.4 on 2024-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0025_rename_quote_1_project_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_ar',
            field=models.TextField(null=True),
        ),
    ]
