# Generated by Django 5.1.4 on 2024-12-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0027_product_description_en_product_details_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='custom_models.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='custom_models.category'),
            preserve_default=False,
        ),
    ]
