# Generated by Django 5.1.4 on 2024-12-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0028_remove_product_brands_remove_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='products', to='custom_models.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='custom_models.category'),
        ),
    ]
