# Generated by Django 5.1.4 on 2024-12-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0031_blog_categories_blog_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Blog/'),
        ),
    ]
