# Generated by Django 5.1.4 on 2024-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0032_blog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalinfo',
            name='welcome_message_ar',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
