# Generated by Django 5.1.4 on 2024-12-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0033_remove_globalinfo_welcome_message_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='small_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='welcome_message_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='welcome_message_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='small_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
