# Generated by Django 5.1.4 on 2024-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0034_globalinfo_small_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='is_footer',
            field=models.BooleanField(default=True),
        ),
    ]
