# Generated by Django 5.1.4 on 2024-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0035_companyaddress_is_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='html_content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='html_content_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
