# Generated by Django 5.0.6 on 2024-12-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0036_globalinfo_html_content_globalinfo_html_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='first_has_top_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='first_parent_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_has_top_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='first_has_top_categoryss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_has_top_category', to='custom_models.category'),
        ),
    ]
