# Generated by Django 5.0.6 on 2024-12-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0037_remove_category_first_has_top_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sub_title_ar',
        ),
    ]
