# Generated by Django 5.0.6 on 2024-12-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0038_remove_brand_description_ar_remove_brand_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='custom_models.category'),
        ),
    ]
