# Generated by Django 5.0.6 on 2024-12-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0039_brand_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='العنوان')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('description_en', models.TextField(null=True, verbose_name='الوصف')),
                ('description_ar', models.TextField(null=True, verbose_name='الوصف')),
                ('html_content', models.TextField(blank=True, null=True)),
                ('html_content_en', models.TextField(blank=True, null=True)),
                ('html_content_ar', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق'), ('pending', 'معلق')], default='open', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
    ]
