# Generated by Django 5.0.6 on 2024-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0040_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
