# Generated by Django 5.0.6 on 2024-12-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0041_brand_description_ar_brand_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='website_url',
        ),
    ]
