# Generated by Django 5.0.6 on 2024-12-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0043_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
