# Generated by Django 5.0.6 on 2024-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0044_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='whats_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
