# Generated by Django 5.0.6 on 2024-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0045_globalinfo_whats_phone_alter_globalinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_botton',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_botton_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_botton_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_massage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_massage_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_product_massage_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
