# Generated by Django 5.0.6 on 2024-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0046_globalinfo_whats_product_botton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='global_txt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_message', models.CharField(blank=True, max_length=200, null=True)),
                ('Send_message_en', models.CharField(blank=True, max_length=200, null=True)),
                ('Send_message_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('conect_us', models.CharField(blank=True, max_length=200, null=True)),
                ('conect_us_en', models.CharField(blank=True, max_length=200, null=True)),
                ('conect_us_ar', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
