# Generated by Django 5.0.6 on 2024-12-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0047_global_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='View_Project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='View_Project_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='View_Project_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='next_Projects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='next_Projects_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='next_Projects_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
