# Generated by Django 5.0.6 on 2024-12-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0048_global_txt_view_project_global_txt_view_project_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='whats_home_massage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_home_massage_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='whats_home_massage_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
