# Generated by Django 5.1.4 on 2024-12-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0049_globalinfo_whats_home_massage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='in_home',
            field=models.BooleanField(default=False),
        ),
    ]
