# Generated by Django 5.1.4 on 2024-12-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0050_blog_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesstructer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
