# Generated by Django 5.1.4 on 2024-12-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0051_pagesstructer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_home_massage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_home_massage_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_home_massage_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_botton',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_botton_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_botton_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_massage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_massage_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='whats_product_massage_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
