# Generated by Django 5.1.4 on 2024-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0052_alter_globalinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='sub_title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
