# Generated by Django 5.1.4 on 2024-12-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0053_alter_companyaddress_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='Brands',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='Brands_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='Brands_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='category_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='category_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
