# Generated by Django 5.1.4 on 2024-12-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0054_global_txt_brands_global_txt_brands_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand2', to='custom_models.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand3', to='custom_models.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand4', to='custom_models.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand5', to='custom_models.category'),
        ),
    ]
