# Generated by Django 5.1.4 on 2024-12-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0055_brand_categories2_brand_categories3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categoriesAll',
            field=models.ManyToManyField(blank=True, related_name='brandsall', to='custom_models.category'),
        ),
    ]
