# Generated by Django 5.0.3 on 2025-02-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0056_brand_categoriesall'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
