# Generated by Django 5.0.3 on 2025-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0057_product_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
