# Generated by Django 5.0.3 on 2025-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0058_blog_visit_count_brand_visit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='bkcolor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
