# Generated by Django 5.0.3 on 2025-03-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0059_global_txt_bkcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='العنوان الذي سيظهر للمستخدم', max_length=255)),
                ('file', models.FileField(upload_to='product_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='custom_models.filetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='custom_models.product')),
            ],
        ),
    ]
