# Generated by Django 5.0.3 on 2025-03-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0062_job_file_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='file_types',
        ),
        migrations.AddField(
            model_name='contact',
            name='file_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfss', to='custom_models.filetype'),
        ),
    ]
