# Generated by Django 5.0.3 on 2025-03-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0063_remove_job_file_types_contact_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_models.product'),
        ),
    ]
