# Generated by Django 5.0.3 on 2025-03-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0064_contact_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestproduct',
            name='file_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfsss', to='custom_models.filetype'),
        ),
    ]
