# Generated by Django 5.0.3 on 2025-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0065_requestproduct_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
