# Generated by Django 5.0.3 on 2025-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0066_filetype_description_ar_filetype_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestproduct',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
