# Generated by Django 5.0.3 on 2025-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0067_alter_requestproduct_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='brand_title_section',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
