# Generated by Django 5.0.3 on 2025-03-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0068_global_txt_brand_title_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='brand_title_section_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='brand_title_section_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
