# Generated by Django 5.0.3 on 2025-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0069_global_txt_brand_title_section_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='faq_img',
            field=models.ImageField(blank=True, null=True, upload_to='faq_img/'),
        ),
    ]
