# Generated by Django 5.0.3 on 2025-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0070_global_txt_faq_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='toast_massage_form_product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
