# Generated by Django 5.0.3 on 2025-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0071_global_txt_toast_massage_form_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_txt',
            name='toast_massage_form_product_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='global_txt',
            name='toast_massage_form_product_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
